### ISSUE TITLE
OOM Exceptions from volley

### ISSUE THREAD

**Issue by xp-vit** [RandoApp/Rando-android#114]
java.lang.OutOfMemoryError
            at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:101)
            at com.android.volley.toolbox.PoolingByteArrayOutputStream.<init>(PoolingByteArrayOutputStream.java:53)
            at com.android.volley.toolbox.BasicNetwork.entityToBytes(BasicNetwork.java:210)
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:106)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:105)

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
