### ISSUE TITLE
NPE on Auth by email and password

### ISSUE THREAD

**Issue by xp-vit** [RandoApp/Rando-android#149]
{"STACK_TRACE":"java.lang.NullPointerException
	at com.github.randoapp.auth.BaseAuth.hideSoftKeyboard(BaseAuth.java:37)
	at com.github.randoapp.auth.BaseAuth.done(BaseAuth.java:27)
	at com.github.randoapp.auth.EmailAndPasswordAuth$2.onOk(EmailAndPasswordAuth.java:60)
	at com.github.randoapp.task.BaseTask.triggerCallback(BaseTask.java:58)
	at com.github.randoapp.task.BaseTask.onPostExecute(BaseTask.java:46)
	at com.github.randoapp.task.BaseTask.onPostExecute(BaseTask.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4944)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)
",
"PHONE_MODEL":"GT-S6810B",
"APP_VERSION_NAME":"1.0.1",
"ANDROID_VERSION":"4.1.2",
"USER_APP_START_DATE":"2014-05-06T22:34:10.000+00:00",
"APP_VERSION_CODE":3}

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
