### ISSUE TITLE
NPE in Toast create logic

### ISSUE THREAD

**Issue by xp-vit** [RandoApp/Rando-android#153]
{"STACK_TRACE":"java.lang.NullPointerException
	at android.widget.Toast.<init>(Toast.java:105)
	at android.widget.Toast.makeText(Toast.java:261)
	at com.github.randoapp.auth.SkipAuth$1.onError(SkipAuth.java:39)
	at com.github.randoapp.task.BaseTask.triggerCallback(BaseTask.java:60)
	at com.github.randoapp.task.BaseTask.onPostExecute(BaseTask.java:46)
	at com.github.randoapp.task.BaseTask.onPostExecute(BaseTask.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
	at dalvik.system.NativeStart.main(Native Method)
",
"PHONE_MODEL":"GT-N7100",
"APP_VERSION_NAME":"1.0.1",
"ANDROID_VERSION":4.3,
"USER_APP_START_DATE":"2014-05-07T14:36:44.000+05:30",
"APP_VERSION_CODE":3}

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
