### ISSUE TITLE
IllegalStateException on "MI 2S" after Logout

### ISSUE THREAD

**Issue by xp-vit** [RandoApp/Rando-android#158]
{"STACK_TRACE":"java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1354)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1372)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
	at com.github.randoapp.menu.LogoutMenu$1.onDone(LogoutMenu.java:32)
	at com.github.randoapp.task.BaseTask.triggerCallback(BaseTask.java:64)
	at com.github.randoapp.task.BaseTask.onPostExecute(BaseTask.java:46)
	at com.github.randoapp.task.BaseTask.onPostExecute(BaseTask.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:631)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4881)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:804)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:571)
	at dalvik.system.NativeStart.main(Native Method)
"
"PHONE_MODEL":"MI 2S"
"APP_VERSION_NAME":"1.0.1"
"ANDROID_VERSION":"4.1.1"
"USER_APP_START_DATE":"2014-05-08T08:20:37.000+08:00"
"APP_VERSION_CODE":3}

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
