### ISSUE TITLE
OOM on MainActivity

### ISSUE THREAD

**Issue by xp-vit** [RandoApp/Rando-android#192]
{"STACK_TRACE":"java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at com.github.randoapp.util.BitmapUtil.decodeSampledBitmap(BitmapUtil.java:43)
	at com.github.randoapp.adapter.RandoPairsAdapter.loadFile(RandoPairsAdapter.java:317)
	at com.github.randoapp.adapter.RandoPairsAdapter.loadImages(RandoPairsAdapter.java:303)
	at com.github.randoapp.adapter.RandoPairsAdapter.getView(RandoPairsAdapter.java:110)
	at com.jess.ui.TwoWayAbsListView.obtainView(TwoWayAbsListView.java:1505)
	at com.jess.ui.TwoWayGridView$VerticalGridBuilder.onMeasure(TwoWayGridView.java:1619)
	at com.jess.ui.TwoWayGridView.onMeasure(TwoWayGridView.java:284)
	at android.view.View.measure(View.java:16829)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
	at android.view.View.measure(View.java:16829)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16829)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16829)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16829)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16829)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2581)
	at android.view.View.measure(View.java:16829)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2186)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1349)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1532)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6340)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5454)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	at dalvik.system.NativeStart.main(Native Method)
","PHONE_MODEL":"SM-N900L","APP_VERSION_NAME":"1.0.10","ANDROID_VERSION":4.3,"USER_APP_START_DATE":"2014-06-27T21:23:16.000+09:00","APP_VERSION_CODE":23}

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
