### ISSUE TITLE
OOM in SquareTask 

### ISSUE THREAD

**Issue by xp-vit** [RandoApp/Rando-android#196]
{"STACK_TRACE":"java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:628)
	at com.commonsware.cwac.camera.SquareTask.saveSquareImage(SquareTask.java:101)
	at com.commonsware.cwac.camera.SquareTask.run(SquareTask.java:162)
","PHONE_MODEL":"GT-I9195","APP_VERSION_NAME":"1.0.10","ANDROID_VERSION":"4.2.2","USER_APP_START_DATE":"2014-06-27T17:06:24.000-03:00","APP_VERSION_CODE":23}

**Comment by xp-vit** [comment]
It will be reopen if still exist in new version.
